services:
  ui:
    image: test_ui
    build:
      context: .
      dockerfile: containers/ui/Dockerfile
    ports:
      - 8000:80
  api:
    image: test_api
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    ports:
      - 8080:8080
    environment:
      TEST: "BONG"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres

  keycloak:
    <<: *type
    image: "quay.io/keycloak/keycloak:23.0"
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - ${KEYCLOAK_PORT}:8080
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
      start_interval: 10s
    volumes:
      - ./dev/keycloak:/opt/keycloak/data/import

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      FRONTEND_HOST: ${FRONTEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOST: ${BACKEND_HOST}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./dev/nginx:/etc/nginx/templates:ro
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_vol:/var/lib/postgresql/data

volumes:
  postgres_vol:
