ui:
  port: 8000
  targetPort: 80
  image: rodycaymond/test-image-suite
  tag: latest
  name: frontend

api:
  port: 8080
  targetPort: 8080
  image: rodycaymond/test-api
  tag: latest
  name: backend
  environment:
    TEST: "BONG"

db:
  image: postgres
  tag: latest
  serviceName: postgres
  port: 5432
  targetPort: 5423
  DB_NAME: test_database
  DB_PORT: 5432
  DB_USER: admin
  DB_PASSWORD: password
  DB_HOST: postgres

ingress:
  name: nginx-server
  FRONTEND_HOST: frontend.default.svc.cluster.local
  FRONTEND_PORT: 8000
  BACKEND_HOST: backend.default.svc.cluster.local
  BACKEND_PORT: 8080

app:
  name: test-app

config:
  configFile: |-
    # Client configs
    redirect_url=               "/oauth2/callback"
    oidc_issuer_url=            "https://keycloak.test.cody/realms/zeus-apps"
    client_id=                  "test-app"
    client_secret=              "52f81DodPlYafGR23xJenW6UXizwOv0H"
    cookie_secret=              "68W9GCfJxthaPQFZ3itOJ48HBNFzDTt0iZtfP1L8YjI="
    cookie_name=                "__Secure-oauth_proxy_test-app"
    upstreams=                  "http://helm.test.cody"

    # Allowed roles configs
    allowed_roles=               ["test-app:OWNER", "test-app:DEVELOPER", "test-app:GUEST"]
    allowed_groups=              ["*"]

    # Redis configs
    redis_connection_url=       "redis://redis:6379"
    session_store_type=         "redis"

    # Cookie confs
    cookie_refresh=             "60s"
    cookie_secure=              "true"

    # Additional configs
    provider=                   "keycloak-oidc"
    email_domains=              ["*"]
    http_address=               "0.0.0.0:4180"
    reverse_proxy=              "true"
    set_authorization_header=   "true"
