apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: LoadBalancer
