apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.api.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.api.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.api.name }}"
    spec:
      initContainers:
        - name: check-db-ready
          image: "{{ .Values.db.image}}:{{ .Values.db.tag }}"
          command: [
              "sh",
              "-c",
              "until pg_isready -h {{ .Values.db.DB_HOST }} -p 5432;
              do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: "{{ .Values.api.name }}"
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: TEST
              value: "{{ .Values.api.environment.TEST }}"
            - name: POSTGRES_DB
              value: "{{ .Values.db.DB_NAME }}"
            - name: POSTGRES_USER
              value: "{{ .Values.db.DB_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.db.DB_PASSWORD }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.db.DB_PORT }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.db.DB_HOST }}"
