apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: TEST
              value: {{ .Values.api.environment.TEST | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db.DB_NAME | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.DB_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.DB_PASSWORD | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.db.DB_PORT | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.db.DB_HOST | quote }}
