apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
spec:
  selector:
    app: {{ .Values.ui.name }}
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: 80
  type: LoadBalancer
