apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.name }}"
  annotations:
    alb.ingress.kubernetes.io/auth-type: "keycloak-oidc"
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer": "https://keycloak.zeus.socom.dev/realms/zeus-apps", "authenticationEndoint": "", "secretName": "my-auth-secret"}'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate 
spec:
  ingressClassName: alb
  rules:
    - host: helm.test.cody
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: "{{ .Values.ui.name }}"
                port:
                  number: 8000
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: "{{ .Values.api.name }}"
                port:
                  number: 8080
