apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: 4180
    targetPort: 4180

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      annotations:
        {{ tpl .Values.config.configFile }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: docker.io/bitnami/oauth2-proxy:7.6.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4180
